# Generated by Django 4.2.6 on 2023-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebName', models.CharField(blank=True, max_length=100, null=True)),
                ('WebAbout', models.CharField(blank=True, max_length=100, null=True)),
                ('WebImage', models.ImageField(blank=True, null=True, upload_to='WEBIMAGE')),
            ],
        ),
    ]
