# Generated by Django 4.2.6 on 2023-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_websitedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(blank=True, max_length=100, null=True)),
                ('Pemail', models.CharField(blank=True, max_length=100, null=True)),
                ('Pgender', models.CharField(blank=True, max_length=100, null=True)),
                ('Plocation', models.CharField(blank=True, max_length=100, null=True)),
                ('Poccupation', models.CharField(blank=True, max_length=100, null=True)),
                ('Pcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('pDOV', models.CharField(blank=True, max_length=100, null=True)),
                ('pamount', models.IntegerField(blank=True, null=True)),
                ('Pabout', models.CharField(blank=True, max_length=100, null=True)),
                ('Pimage', models.ImageField(blank=True, null=True, upload_to='PIMAGE')),
            ],
        ),
    ]
