# Generated by Django 4.2.6 on 2023-12-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_campdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampDB',
        ),
    ]
