# Generated by Django 4.2.6 on 2023-11-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='campDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EName', models.CharField(blank=True, max_length=100, null=True)),
                ('EMobile', models.IntegerField(blank=True, null=True)),
                ('Eemail', models.CharField(blank=True, max_length=100, null=True)),
                ('Event', models.CharField(blank=True, max_length=100, null=True)),
                ('Elocation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
