# Generated by Django 4.2.6 on 2023-11-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_campdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contributionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(blank=True, max_length=100, null=True)),
                ('CMobile', models.IntegerField(blank=True, null=True)),
                ('Cemail', models.CharField(blank=True, max_length=100, null=True)),
                ('Cmessage', models.CharField(blank=True, max_length=100, null=True)),
                ('Ccategory', models.CharField(blank=True, max_length=100, null=True)),
                ('Coccupation', models.CharField(blank=True, max_length=100, null=True)),
                ('Camount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='itemsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IName', models.CharField(blank=True, max_length=100, null=True)),
                ('IMobile', models.IntegerField(blank=True, null=True)),
                ('Iemail', models.CharField(blank=True, max_length=100, null=True)),
                ('Ilocation', models.CharField(blank=True, max_length=100, null=True)),
                ('Iitem', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
