# Generated by Django 4.2.6 on 2023-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_contributiondb_itemsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='campdb',
            name='Edate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
