# Generated by Django 4.2.6 on 2023-12-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_campdb_edate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdb',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='contactdb',
            name='UName',
        ),
    ]
