# Generated by Django 4.2.6 on 2023-12-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_delete_contactdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='campDB',
        ),
    ]
